In [1]:
import pandas as pd
import numpy as np
from Neural_Network import Neural_Network

In [2]:
iris = pd.read_csv('datasets/iris.csv')
iris

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
iris['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [4]:
iris_setosa = iris.copy()
iris_setosa['species'] = iris_setosa['species'].apply(lambda s: 1 if s == 'Iris-setosa' else 0)
iris_setosa

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        0
146           6.3          2.5           5.0          1.9        0
147           6.5          3.0           5.2          2.0        0
148           6.2          3.4           5.4          2.3        0
149           5.9          3.0           5.1          1.8        0

[150 rows x 5 columns]

In [5]:
iris_versicolor = iris.copy()
iris_versicolor['species'] = iris_versicolor['species'].apply(lambda s: 1 if s == 'Iris-versicolor' else 0)
iris_versicolor

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        0
146           6.3          2.5           5.0          1.9        0
147           6.5          3.0           5.2          2.0        0
148           6.2          3.4           5.4          2.3        0
149           5.9          3.0           5.1          1.8        0

[150 rows x 5 columns]

In [6]:
iris_virginica = iris.copy()
iris_virginica['species'] = iris_virginica['species'].apply(lambda s: 1 if s == 'Iris-virginica' else 0)
iris_virginica

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        1
146           6.3          2.5           5.0          1.9        1
147           6.5          3.0           5.2          2.0        1
148           6.2          3.4           5.4          2.3        1
149           5.9          3.0           5.1          1.8        1

[150 rows x 5 columns]

In [7]:
species = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
iris_species = iris.copy()
iris_species = pd.get_dummies(iris, columns=['species'])
iris_species

sepal_length  sepal_width  petal_length  petal_width  \
0             5.1          3.5           1.4          0.2   
1             4.9          3.0           1.4          0.2   
2             4.7          3.2           1.3          0.2   
3             4.6          3.1           1.5          0.2   
4             5.0          3.6           1.4          0.2   
..            ...          ...           ...          ...   
145           6.7          3.0           5.2          2.3   
146           6.3          2.5           5.0          1.9   
147           6.5          3.0           5.2          2.0   
148           6.2          3.4           5.4          2.3   
149           5.9          3.0           5.1          1.8   

     species_Iris-setosa  species_Iris-versicolor  species_Iris-virginica  
0                      1                        0                       0  
1                      1                        0                       0  
2                      1                        0                       0  
3                      1                        0                       0  
4                      1                        0                       0  
..                   ...                      ...                     ...  
145                    0                        0                       1  
146                    0                        0                       1  
147                    0                        0                       1  
148                    0                        0                       1  
149                    0                        0                       1  

[150 rows x 7 columns]

In [8]:
nw = Neural_Network(examples=iris_species, 
                    indepedent_vars=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'],
                    dependent_var=['species_Iris-setosa', 'species_Iris-versicolor', 'species_Iris-virginica'],
                    num_hidden_layers=5,
                    neurons_per_layer=[1,2,3,4,5])
nw.cross_validation(0.8)

Values for output layer neurons:  0.9489694501692402
Magic number 2:  12.856130484030443
Magic number 2:  3.08299876956531
Magic number 2:  12.86569338341974
Magic number 2:  14.063778340744683
Magic number 2:  19.120008528137948
Magic number 2:  2.537322463870559
Magic number 2:  1.5044977494767542
Magic number 2:  1.966878844104921
Magic number 2:  2.91139585462244
Magic number 2:  0.3049163191808554
Magic number 2:  0.38893766639528393
Magic number 2:  0.36314755726660886
Magic number 2:  0.032773662253468436
Magic number 2:  0.054627024564521676
Magic number 2:  0.00011545570606349025
0
[0.13386068 0.16694647 0.63429791 0.91757508 0.99998237] 
1
[0.16717933 1.00000068] 
[0.34444749 1.        ] 
2
[0.49876081 0.42869937 1.00004214] 
[0.08111457 0.48266165 1.00005074] 
[0.51971014 0.44800822 1.        ] 
3
[0.33464342 0.33440612 0.19111676 1.00027726] 
[0.17657688 0.73098266 0.36548299 1.00018803] 
[0.62378798 0.44330507 0.87083681 1.00021126] 
[0.1271241  0.48440793 0.32698703 1.   

OverflowError: math range error

In [ ]:
iris_species

In [ ]:
spambase = pd.read_csv('datasets/spambase.data') ## hay que agregarle manualmente las columnas
spambase

In [ ]:
type(np.ndarray([1,2,3,4]))